### ISSUE TITLE
weblogic 10.3.6.0 搭建失败

### ISSUE THREAD

**Issue by zema1** [QAX-A-Team/WeblogicEnvironment#3]
直接使用配置自带的 `run_weblogic1036jdk6u25.sh` 运行的，报了这样的错误
![image](https://user-images.githubusercontent.com/20637881/76423194-5bf81d80-63e1-11ea-8f38-123649c25935.png)

感觉像是缺了某个 lib，java 没起来. 我猜的原因可能是 centos 更新了，基础镜像有所改动。

求修一下，对这个不太懂。

**Comment by zema1** [comment]
改下 Dockerfile 加入 `yum -y install libnsl` 就可以了。这项目可真是提交不维护系列，咋连个人回复都没有。

**Comment by bibotai** [comment]
你好，近期更新。
