### ISSUE TITLE
ubuntu、centos搭建失败

### ISSUE THREAD

**Issue by secskb** [QAX-A-Team/WeblogicEnvironment#4]
ubuntu版本：2020.04 LTS 64位
centos版本：CentOS 7.8 64位
JDK: 7u21 8u121
Weblogic 版本：fmw_12.1.3.0.0_wls.jar

除以上外，还有其它jdk版本测试失败
这里是运行的脚本，还有自己输入参数的也失败。

![image](https://user-images.githubusercontent.com/34313868/111566405-0f0b0c00-87d8-11eb-9943-3d5bdb3f530e.png)

**Comment by bibotai** [comment]
近期空下来我会测试一下，修复下相关问题，感谢issue
